apiVersion: v2
name: haos-one
description: Run Home Assistant OS in a single container on Kubernetes.
type: application
version: 0.0.2
appVersion: "latest"
icon: https://www.home-assistant.io/images/favicon-192x192.png
