replicaCount: 1

image:
  repository: qweritos/haos-one
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

hostNetwork: false

service:
  enabled: true
  type: ClusterIP
  port: 8123

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: haos.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s
  path: /api/prometheus
  scheme: http
  honorLabels: false
  labels:
    release: kube-prometheus-stack

persistence:
  enabled: false
  mountPath: /mnt/data
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClass: ""
  existingClaim: ""
  hostPath: ""

securityContext:
  privileged: true

apparmor:
  unconfined: true

podAnnotations: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
