{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "haos-one.fullname" . }}
  labels:
    {{- include "haos-one.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ include "haos-one.servicePortName" . }}
      port: {{ .Values.service.port }}
      targetPort: {{ include "haos-one.servicePortName" . }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "haos-one.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
