apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "haos-one.fullname" . }}
  labels:
    {{- include "haos-one.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "haos-one.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "haos-one.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "haos-one.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{- if or .Values.apparmor.unconfined .Values.podAnnotations }}
      annotations:
        {{- if .Values.apparmor.unconfined }}
        container.apparmor.security.beta.kubernetes.io/haos-one: unconfined
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: {{ ternary "ClusterFirstWithHostNet" "ClusterFirst" .Values.hostNetwork }}
      containers:
        - name: haos-one
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: {{ .Values.securityContext.privileged }}
          {{- if .Values.service.enabled }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- end }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}
          {{- if .Values.apparmor.unconfined }}
            - name: host-security
              mountPath: /sys/kernel/security
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      {{- if .Values.persistence.enabled }}
        {{- if .Values.persistence.hostPath }}
        - name: data
          hostPath:
            path: {{ .Values.persistence.hostPath }}
            type: DirectoryOrCreate
        {{- else if .Values.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
        {{- else }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "haos-one.fullname" . }}
        {{- end }}
      {{- end }}
      {{- if .Values.apparmor.unconfined }}
        - name: host-security
          hostPath:
            path: /sys/kernel/security
            type: ""
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
